# Generated by Django 6.0 on 2025-12-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/pets/'),
        ),
    ]
