# Generated by Django 6.0 on 2025-12-31 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_adoption', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='bio',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='interest',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('adoption', 'Adoption Inquiry'), ('volunteering', 'Volunteering'), ('donation', 'Donation Support'), ('feedback', 'Feedback'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='roles',
            field=models.TextField(blank=True, help_text='Comma-separated list of selected roles', null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='weekly_hours',
            field=models.CharField(blank=True, help_text='e.g., 2-5, 5-10, 10+', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
